[project]
name = "ai-fairytale-post"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.61.1",
    "requests>=2.32.3",
]
